version: '3.8'

services:
  smith:
    image: ghcr.io/ksanivesela/hola_flask-replica:latest

    networks:
      - traefik-public

    deploy:
      replicas: 1

      update_config:
        parallelism: 1
        delay: 10s

      restart_policy:
        condition: on-failure

      labels:
        - "traefik.enable=true"

        # HTTP
        - "traefik.http.routers.smith.rule=Host(`smith.byronrm.com`)"
        - "traefik.http.routers.smith.entrypoints=http"
        - "traefik.http.routers.smith.middlewares=smith-https-redirect"

        # Redirect HTTP → HTTPS
        - "traefik.http.middlewares.smith-https-redirect.redirectscheme.scheme=https"

        # HTTPS
        - "traefik.http.routers.smith-secure.rule=Host(`smith.byronrm.com`)"
        - "traefik.http.routers.smith-secure.entrypoints=https"
        - "traefik.http.routers.smith-secure.tls=true"
        - "traefik.http.routers.smith-secure.tls.certresolver=http"

        # Service (puerto interno del contenedor)
        - "traefik.http.services.smith.loadbalancer.server.port=5000"

        # Red de Traefik
        - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true