name: Publicar Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  publicar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Login en GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir y publicar imagen
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/ksanivesela/hola_flask-replica:latest

      - name: Mostrar datos de conexión
        run: |
          echo "Host: ${{ secrets.VPS_HOST }}"
          echo "Usuario: ${{ secrets.VPS_USER }}"
          echo "Puerto: ${{ secrets.VPS_SSH_PORT }}"

      - name: Probar conexión SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Conexion SSH OK"
            mkdir -p ~/landinga

      - name: Copiar archivos al VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: "stack.yml,Makefile"
          target: "/home/${{ secrets.VPS_USER }}/landinga"

      - name: Desplegar en VPS (Docker Swarm)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "🚀 Desplegando servicios"

            cd ~/landinga

            echo "📦 Pull imagen..."
            docker pull ghcr.io/ksanivesela/hola_flask-replica:latest

            echo "⚙️ Deploy stack..."
            docker stack deploy -c stack.yml borrar

            echo "⏳ Esperando a que el servicio levante..."

            for i in {1..10}; do
              REPLICAS=$(docker service ls --filter name=borrar_smith --format "{{.Replicas}}")

              if [[ "$REPLICAS" == "1/1" ]]; then
                echo "✅ Servicio listo!"
                docker service ls
                exit 0
              fi

              echo "⌛ Aún no listo ($REPLICAS)... esperando"
              sleep 3
            done

            echo "❌ Error: servicio no levantó"
            docker service ls
            exit 1